
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package palamod.init;

import palamod.world.inventory.XpbushpalahelpguiMenu;
import palamod.world.inventory.WipguiMenu;
import palamod.world.inventory.VoidstoneminerconfigMenu;
import palamod.world.inventory.UploaderguipalahelpMenu;
import palamod.world.inventory.UploaderguiMenu;
import palamod.world.inventory.TrixiumdepositMenu;
import palamod.world.inventory.TrashguiMenu;
import palamod.world.inventory.TitanechestguiMenu;
import palamod.world.inventory.TemporymarketMenu;
import palamod.world.inventory.StockhdvMenu;
import palamod.world.inventory.Stickgui7Menu;
import palamod.world.inventory.Stickgui6Menu;
import palamod.world.inventory.Stickgui5Menu;
import palamod.world.inventory.Stickgui4Menu;
import palamod.world.inventory.Stickgui3Menu;
import palamod.world.inventory.Stickgui2Menu;
import palamod.world.inventory.Stickgui1Menu;
import palamod.world.inventory.StatusdevnoteMenu;
import palamod.world.inventory.SpecialmoneypanelMenu;
import palamod.world.inventory.SpawnpanelMenu;
import palamod.world.inventory.SafeguiMenu;
import palamod.world.inventory.PotgtranfertMenu;
import palamod.world.inventory.PhoneguiMenu;
import palamod.world.inventory.PalamachinepalahelpguiMenu;
import palamod.world.inventory.PalamachineguiMenu;
import palamod.world.inventory.PalahelptreeMenu;
import palamod.world.inventory.PalahelporeMenu;
import palamod.world.inventory.PalahelpnotsupportedMenu;
import palamod.world.inventory.PalahelpmachineMenu;
import palamod.world.inventory.Palahelpgui1Menu;
import palamod.world.inventory.PalahelpblockMenu;
import palamod.world.inventory.PalaerrorMenu;
import palamod.world.inventory.Palaerror0006Menu;
import palamod.world.inventory.Palaerror0005Menu;
import palamod.world.inventory.Palaerror0004Menu;
import palamod.world.inventory.Palaerror0003Menu;
import palamod.world.inventory.Palaerror0001Menu;
import palamod.world.inventory.PaladumfurnaceMenu;
import palamod.world.inventory.PaladiumchestguiMenu;
import palamod.world.inventory.OrelayerfatMenu;
import palamod.world.inventory.NextPalahelpguiMenu;
import palamod.world.inventory.MoneypanelMenu;
import palamod.world.inventory.MegasafechestfirstsetupMenu;
import palamod.world.inventory.LuckyguiMenu;
import palamod.world.inventory.LegendarystonepalahelpMenu;
import palamod.world.inventory.LanguageselectionMenu;
import palamod.world.inventory.ItemmenupalahelpMenu;
import palamod.world.inventory.Hdvv3Menu;
import palamod.world.inventory.HdvsellguiMenu;
import palamod.world.inventory.HdvhelpMenu;
import palamod.world.inventory.Hdvguiv2Menu;
import palamod.world.inventory.HdvguiMenu;
import palamod.world.inventory.HdvconfguiMenu;
import palamod.world.inventory.GuardianguiMenu;
import palamod.world.inventory.GrindersplitentityMenu;
import palamod.world.inventory.GrinderpalahelpguiMenu;
import palamod.world.inventory.Grinderpalahelp2guiMenu;
import palamod.world.inventory.GrinderguiMenu;
import palamod.world.inventory.GreenpaladiumchestguiMenu;
import palamod.world.inventory.GolemtreecMenu;
import palamod.world.inventory.ForgepalahelpguiMenu;
import palamod.world.inventory.ForgeguiMenu;
import palamod.world.inventory.FluidpalahelpMenu;
import palamod.world.inventory.FactionhomeguiMenu;
import palamod.world.inventory.FactioncreateguiMenu;
import palamod.world.inventory.ExampleuploaderguiMenu;
import palamod.world.inventory.Examplecrusherv2Menu;
import palamod.world.inventory.EndiumchestguiMenu;
import palamod.world.inventory.DownloaderlinkMenu;
import palamod.world.inventory.DownloaderguiMenu;
import palamod.world.inventory.CrusherpalahelpguiMenu;
import palamod.world.inventory.CrusherguiMenu;
import palamod.world.inventory.AuthsafeguiMenu;
import palamod.world.inventory.AssembleurendMenu;
import palamod.world.inventory.ArmorpalahelpguiMenu;
import palamod.world.inventory.AnalyserresultMenu;
import palamod.world.inventory.AnalyserloadingMenu;
import palamod.world.inventory.AmethystchestguiMenu;
import palamod.world.inventory.AlchemycreatorguiMenu;
import palamod.world.inventory.AdminshoporetitaneMenu;
import palamod.world.inventory.AdminshoporepaladiumMenu;
import palamod.world.inventory.AdminshoporeironMenu;
import palamod.world.inventory.AdminshoporegoldMenu;
import palamod.world.inventory.AdminshoporefindiumMenu;
import palamod.world.inventory.AdminshoporediamondMenu;
import palamod.world.inventory.AdminshoporecoalMenu;
import palamod.world.inventory.AdminshoporeamethystMenu;
import palamod.world.inventory.AdminshoporeMenu;
import palamod.world.inventory.AdminshopmenuMenu;
import palamod.world.inventory.AdminshopblockstoneMenu;
import palamod.world.inventory.AdminshopblocksoulsandMenu;
import palamod.world.inventory.AdminshopblockoakwoodMenu;
import palamod.world.inventory.AdminshopblockgrassMenu;
import palamod.world.inventory.AdminshopblockblackstoneMenu;
import palamod.world.inventory.AdminshopblockSandMenu;
import palamod.world.inventory.AdminshopblockNetherrackMenu;
import palamod.world.inventory.AdminshopblockMenu;
import palamod.world.inventory.AdminshopblockGravelMenu;
import palamod.world.inventory.AdminshopblockGlowstoneMenu;
import palamod.world.inventory.AdminshopblockDirtMenu;
import palamod.world.inventory.AdminshopadbanMenu;
import palamod.world.inventory.AdminpanelmenuMenu;

import net.minecraftforge.network.IContainerFactory;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.event.RegistryEvent;

import net.minecraft.world.inventory.MenuType;
import net.minecraft.world.inventory.AbstractContainerMenu;

import java.util.List;
import java.util.ArrayList;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class PalamodModMenus {
	private static final List<MenuType<?>> REGISTRY = new ArrayList<>();
	public static final MenuType<CrusherguiMenu> CRUSHERGUI = register("crushergui", (id, inv, extraData) -> new CrusherguiMenu(id, inv, extraData));
	public static final MenuType<PalamachineguiMenu> PALAMACHINEGUI = register("palamachinegui", (id, inv, extraData) -> new PalamachineguiMenu(id, inv, extraData));
	public static final MenuType<GrinderguiMenu> GRINDERGUI = register("grindergui", (id, inv, extraData) -> new GrinderguiMenu(id, inv, extraData));
	public static final MenuType<AlchemycreatorguiMenu> ALCHEMYCREATORGUI = register("alchemycreatorgui", (id, inv, extraData) -> new AlchemycreatorguiMenu(id, inv, extraData));
	public static final MenuType<Palahelpgui1Menu> PALAHELPGUI_1 = register("palahelpgui_1", (id, inv, extraData) -> new Palahelpgui1Menu(id, inv, extraData));
	public static final MenuType<NextPalahelpguiMenu> NEXT_PALAHELPGUI = register("next_palahelpgui", (id, inv, extraData) -> new NextPalahelpguiMenu(id, inv, extraData));
	public static final MenuType<PalahelpblockMenu> PALAHELPBLOCK = register("palahelpblock", (id, inv, extraData) -> new PalahelpblockMenu(id, inv, extraData));
	public static final MenuType<ForgeguiMenu> FORGEGUI = register("forgegui", (id, inv, extraData) -> new ForgeguiMenu(id, inv, extraData));
	public static final MenuType<PalahelporeMenu> PALAHELPORE = register("palahelpore", (id, inv, extraData) -> new PalahelporeMenu(id, inv, extraData));
	public static final MenuType<PalahelptreeMenu> PALAHELPTREE = register("palahelptree", (id, inv, extraData) -> new PalahelptreeMenu(id, inv, extraData));
	public static final MenuType<PalahelpmachineMenu> PALAHELPMACHINE = register("palahelpmachine", (id, inv, extraData) -> new PalahelpmachineMenu(id, inv, extraData));
	public static final MenuType<GrinderpalahelpguiMenu> GRINDERPALAHELPGUI = register("grinderpalahelpgui", (id, inv, extraData) -> new GrinderpalahelpguiMenu(id, inv, extraData));
	public static final MenuType<Grinderpalahelp2guiMenu> GRINDERPALAHELP_2GUI = register("grinderpalahelp_2gui", (id, inv, extraData) -> new Grinderpalahelp2guiMenu(id, inv, extraData));
	public static final MenuType<PalamachinepalahelpguiMenu> PALAMACHINEPALAHELPGUI = register("palamachinepalahelpgui", (id, inv, extraData) -> new PalamachinepalahelpguiMenu(id, inv, extraData));
	public static final MenuType<CrusherpalahelpguiMenu> CRUSHERPALAHELPGUI = register("crusherpalahelpgui", (id, inv, extraData) -> new CrusherpalahelpguiMenu(id, inv, extraData));
	public static final MenuType<ForgepalahelpguiMenu> FORGEPALAHELPGUI = register("forgepalahelpgui", (id, inv, extraData) -> new ForgepalahelpguiMenu(id, inv, extraData));
	public static final MenuType<FluidpalahelpMenu> FLUIDPALAHELP = register("fluidpalahelp", (id, inv, extraData) -> new FluidpalahelpMenu(id, inv, extraData));
	public static final MenuType<ItemmenupalahelpMenu> ITEMMENUPALAHELP = register("itemmenupalahelp", (id, inv, extraData) -> new ItemmenupalahelpMenu(id, inv, extraData));
	public static final MenuType<LegendarystonepalahelpMenu> LEGENDARYSTONEPALAHELP = register("legendarystonepalahelp", (id, inv, extraData) -> new LegendarystonepalahelpMenu(id, inv, extraData));
	public static final MenuType<Stickgui1Menu> STICKGUI_1 = register("stickgui_1", (id, inv, extraData) -> new Stickgui1Menu(id, inv, extraData));
	public static final MenuType<Stickgui2Menu> STICKGUI_2 = register("stickgui_2", (id, inv, extraData) -> new Stickgui2Menu(id, inv, extraData));
	public static final MenuType<Stickgui3Menu> STICKGUI_3 = register("stickgui_3", (id, inv, extraData) -> new Stickgui3Menu(id, inv, extraData));
	public static final MenuType<Stickgui4Menu> STICKGUI_4 = register("stickgui_4", (id, inv, extraData) -> new Stickgui4Menu(id, inv, extraData));
	public static final MenuType<Stickgui5Menu> STICKGUI_5 = register("stickgui_5", (id, inv, extraData) -> new Stickgui5Menu(id, inv, extraData));
	public static final MenuType<Stickgui6Menu> STICKGUI_6 = register("stickgui_6", (id, inv, extraData) -> new Stickgui6Menu(id, inv, extraData));
	public static final MenuType<Stickgui7Menu> STICKGUI_7 = register("stickgui_7", (id, inv, extraData) -> new Stickgui7Menu(id, inv, extraData));
	public static final MenuType<ArmorpalahelpguiMenu> ARMORPALAHELPGUI = register("armorpalahelpgui", (id, inv, extraData) -> new ArmorpalahelpguiMenu(id, inv, extraData));
	public static final MenuType<XpbushpalahelpguiMenu> XPBUSHPALAHELPGUI = register("xpbushpalahelpgui", (id, inv, extraData) -> new XpbushpalahelpguiMenu(id, inv, extraData));
	public static final MenuType<LuckyguiMenu> LUCKYGUI = register("luckygui", (id, inv, extraData) -> new LuckyguiMenu(id, inv, extraData));
	public static final MenuType<PaladumfurnaceMenu> PALADUMFURNACE = register("paladumfurnace", (id, inv, extraData) -> new PaladumfurnaceMenu(id, inv, extraData));
	public static final MenuType<SafeguiMenu> SAFEGUI = register("safegui", (id, inv, extraData) -> new SafeguiMenu(id, inv, extraData));
	public static final MenuType<PhoneguiMenu> PHONEGUI = register("phonegui", (id, inv, extraData) -> new PhoneguiMenu(id, inv, extraData));
	public static final MenuType<MegasafechestfirstsetupMenu> MEGASAFECHESTFIRSTSETUP = register("megasafechestfirstsetup", (id, inv, extraData) -> new MegasafechestfirstsetupMenu(id, inv, extraData));
	public static final MenuType<AuthsafeguiMenu> AUTHSAFEGUI = register("authsafegui", (id, inv, extraData) -> new AuthsafeguiMenu(id, inv, extraData));
	public static final MenuType<HdvguiMenu> HDVGUI = register("hdvgui", (id, inv, extraData) -> new HdvguiMenu(id, inv, extraData));
	public static final MenuType<HdvhelpMenu> HDVHELP = register("hdvhelp", (id, inv, extraData) -> new HdvhelpMenu(id, inv, extraData));
	public static final MenuType<HdvsellguiMenu> HDVSELLGUI = register("hdvsellgui", (id, inv, extraData) -> new HdvsellguiMenu(id, inv, extraData));
	public static final MenuType<HdvconfguiMenu> HDVCONFGUI = register("hdvconfgui", (id, inv, extraData) -> new HdvconfguiMenu(id, inv, extraData));
	public static final MenuType<WipguiMenu> WIPGUI = register("wipgui", (id, inv, extraData) -> new WipguiMenu(id, inv, extraData));
	public static final MenuType<TemporymarketMenu> TEMPORYMARKET = register("temporymarket", (id, inv, extraData) -> new TemporymarketMenu(id, inv, extraData));
	public static final MenuType<StatusdevnoteMenu> STATUSDEVNOTE = register("statusdevnote", (id, inv, extraData) -> new StatusdevnoteMenu(id, inv, extraData));
	public static final MenuType<LanguageselectionMenu> LANGUAGESELECTION = register("languageselection", (id, inv, extraData) -> new LanguageselectionMenu(id, inv, extraData));
	public static final MenuType<PalahelpnotsupportedMenu> PALAHELPNOTSUPPORTED = register("palahelpnotsupported", (id, inv, extraData) -> new PalahelpnotsupportedMenu(id, inv, extraData));
	public static final MenuType<PalaerrorMenu> PALAERROR0002 = register("palaerror0002", (id, inv, extraData) -> new PalaerrorMenu(id, inv, extraData));
	public static final MenuType<Palaerror0001Menu> PALAERROR_0001 = register("palaerror_0001", (id, inv, extraData) -> new Palaerror0001Menu(id, inv, extraData));
	public static final MenuType<Palaerror0003Menu> PALAERROR_0003 = register("palaerror_0003", (id, inv, extraData) -> new Palaerror0003Menu(id, inv, extraData));
	public static final MenuType<Palaerror0004Menu> PALAERROR_0004 = register("palaerror_0004", (id, inv, extraData) -> new Palaerror0004Menu(id, inv, extraData));
	public static final MenuType<StockhdvMenu> STOCKHDV = register("stockhdv", (id, inv, extraData) -> new StockhdvMenu(id, inv, extraData));
	public static final MenuType<AdminpanelmenuMenu> ADMINPANELMENU = register("adminpanelmenu", (id, inv, extraData) -> new AdminpanelmenuMenu(id, inv, extraData));
	public static final MenuType<MoneypanelMenu> MONEYPANEL = register("moneypanel", (id, inv, extraData) -> new MoneypanelMenu(id, inv, extraData));
	public static final MenuType<Palaerror0005Menu> PALAERROR_0005 = register("palaerror_0005", (id, inv, extraData) -> new Palaerror0005Menu(id, inv, extraData));
	public static final MenuType<SpawnpanelMenu> SPAWNPANEL = register("spawnpanel", (id, inv, extraData) -> new SpawnpanelMenu(id, inv, extraData));
	public static final MenuType<Palaerror0006Menu> PALAERROR_0006 = register("palaerror_0006", (id, inv, extraData) -> new Palaerror0006Menu(id, inv, extraData));
	public static final MenuType<TrashguiMenu> TRASHGUI = register("trashgui", (id, inv, extraData) -> new TrashguiMenu(id, inv, extraData));
	public static final MenuType<AdminshopmenuMenu> ADMINSHOPMENU = register("adminshopmenu", (id, inv, extraData) -> new AdminshopmenuMenu(id, inv, extraData));
	public static final MenuType<AdminshopblockMenu> ADMINSHOPBLOCK = register("adminshopblock", (id, inv, extraData) -> new AdminshopblockMenu(id, inv, extraData));
	public static final MenuType<Hdvguiv2Menu> HDVGUIV_2 = register("hdvguiv_2", (id, inv, extraData) -> new Hdvguiv2Menu(id, inv, extraData));
	public static final MenuType<VoidstoneminerconfigMenu> VOIDSTONEMINERCONFIG = register("voidstoneminerconfig", (id, inv, extraData) -> new VoidstoneminerconfigMenu(id, inv, extraData));
	public static final MenuType<GuardianguiMenu> GUARDIANGUI = register("guardiangui", (id, inv, extraData) -> new GuardianguiMenu(id, inv, extraData));
	public static final MenuType<GolemtreecMenu> GOLEMTREEC = register("golemtreec", (id, inv, extraData) -> new GolemtreecMenu(id, inv, extraData));
	public static final MenuType<FactioncreateguiMenu> FACTIONCREATEGUI = register("factioncreategui", (id, inv, extraData) -> new FactioncreateguiMenu(id, inv, extraData));
	public static final MenuType<FactionhomeguiMenu> FACTIONHOMEGUI = register("factionhomegui", (id, inv, extraData) -> new FactionhomeguiMenu(id, inv, extraData));
	public static final MenuType<AdminshopadbanMenu> ADMINSHOPADBAN = register("adminshopadban", (id, inv, extraData) -> new AdminshopadbanMenu(id, inv, extraData));
	public static final MenuType<AssembleurendMenu> ASSEMBLEUREND = register("assembleurend", (id, inv, extraData) -> new AssembleurendMenu(id, inv, extraData));
	public static final MenuType<AnalyserloadingMenu> ANALYSERLOADING = register("analyserloading", (id, inv, extraData) -> new AnalyserloadingMenu(id, inv, extraData));
	public static final MenuType<AnalyserresultMenu> ANALYSERRESULT = register("analyserresult", (id, inv, extraData) -> new AnalyserresultMenu(id, inv, extraData));
	public static final MenuType<AdminshoporeMenu> ADMINSHOPORE = register("adminshopore", (id, inv, extraData) -> new AdminshoporeMenu(id, inv, extraData));
	public static final MenuType<AdminshoporepaladiumMenu> ADMINSHOPOREPALADIUM = register("adminshoporepaladium", (id, inv, extraData) -> new AdminshoporepaladiumMenu(id, inv, extraData));
	public static final MenuType<AdminshoporetitaneMenu> ADMINSHOPORETITANE = register("adminshoporetitane", (id, inv, extraData) -> new AdminshoporetitaneMenu(id, inv, extraData));
	public static final MenuType<AdminshoporeamethystMenu> ADMINSHOPOREAMETHYST = register("adminshoporeamethyst", (id, inv, extraData) -> new AdminshoporeamethystMenu(id, inv, extraData));
	public static final MenuType<AdminshoporediamondMenu> ADMINSHOPOREDIAMOND = register("adminshoporediamond", (id, inv, extraData) -> new AdminshoporediamondMenu(id, inv, extraData));
	public static final MenuType<AdminshoporecoalMenu> ADMINSHOPORECOAL = register("adminshoporecoal", (id, inv, extraData) -> new AdminshoporecoalMenu(id, inv, extraData));
	public static final MenuType<AdminshoporegoldMenu> ADMINSHOPOREGOLD = register("adminshoporegold", (id, inv, extraData) -> new AdminshoporegoldMenu(id, inv, extraData));
	public static final MenuType<AdminshoporeironMenu> ADMINSHOPOREIRON = register("adminshoporeiron", (id, inv, extraData) -> new AdminshoporeironMenu(id, inv, extraData));
	public static final MenuType<AdminshoporefindiumMenu> ADMINSHOPOREFINDIUM = register("adminshoporefindium", (id, inv, extraData) -> new AdminshoporefindiumMenu(id, inv, extraData));
	public static final MenuType<AdminshopblockDirtMenu> ADMINSHOPBLOCK_DIRT = register("adminshopblock_dirt", (id, inv, extraData) -> new AdminshopblockDirtMenu(id, inv, extraData));
	public static final MenuType<AdminshopblockstoneMenu> ADMINSHOPBLOCKSTONE = register("adminshopblockstone", (id, inv, extraData) -> new AdminshopblockstoneMenu(id, inv, extraData));
	public static final MenuType<AdminshopblockgrassMenu> ADMINSHOPBLOCKGRASS = register("adminshopblockgrass", (id, inv, extraData) -> new AdminshopblockgrassMenu(id, inv, extraData));
	public static final MenuType<AdminshopblockSandMenu> ADMINSHOPBLOCK_SAND = register("adminshopblock_sand", (id, inv, extraData) -> new AdminshopblockSandMenu(id, inv, extraData));
	public static final MenuType<AdminshopblockNetherrackMenu> ADMINSHOPBLOCK_NETHERRACK = register("adminshopblock_netherrack", (id, inv, extraData) -> new AdminshopblockNetherrackMenu(id, inv, extraData));
	public static final MenuType<AdminshopblockGravelMenu> ADMINSHOPBLOCK_GRAVEL = register("adminshopblock_gravel", (id, inv, extraData) -> new AdminshopblockGravelMenu(id, inv, extraData));
	public static final MenuType<AdminshopblocksoulsandMenu> ADMINSHOPBLOCKSOULSAND = register("adminshopblocksoulsand", (id, inv, extraData) -> new AdminshopblocksoulsandMenu(id, inv, extraData));
	public static final MenuType<AdminshopblockblackstoneMenu> ADMINSHOPBLOCKBLACKSTONE = register("adminshopblockblackstone", (id, inv, extraData) -> new AdminshopblockblackstoneMenu(id, inv, extraData));
	public static final MenuType<AdminshopblockoakwoodMenu> ADMINSHOPBLOCKOAKWOOD = register("adminshopblockoakwood", (id, inv, extraData) -> new AdminshopblockoakwoodMenu(id, inv, extraData));
	public static final MenuType<AdminshopblockGlowstoneMenu> ADMINSHOPBLOCK_GLOWSTONE = register("adminshopblock_glowstone", (id, inv, extraData) -> new AdminshopblockGlowstoneMenu(id, inv, extraData));
	public static final MenuType<UploaderguiMenu> UPLOADERGUI = register("uploadergui", (id, inv, extraData) -> new UploaderguiMenu(id, inv, extraData));
	public static final MenuType<Hdvv3Menu> HDVV_3 = register("hdvv_3", (id, inv, extraData) -> new Hdvv3Menu(id, inv, extraData));
	public static final MenuType<SpecialmoneypanelMenu> SPECIALMONEYPANEL = register("specialmoneypanel", (id, inv, extraData) -> new SpecialmoneypanelMenu(id, inv, extraData));
	public static final MenuType<TitanechestguiMenu> TITANECHESTGUI = register("titanechestgui", (id, inv, extraData) -> new TitanechestguiMenu(id, inv, extraData));
	public static final MenuType<AmethystchestguiMenu> AMETHYSTCHESTGUI = register("amethystchestgui", (id, inv, extraData) -> new AmethystchestguiMenu(id, inv, extraData));
	public static final MenuType<PaladiumchestguiMenu> PALADIUMCHESTGUI = register("paladiumchestgui", (id, inv, extraData) -> new PaladiumchestguiMenu(id, inv, extraData));
	public static final MenuType<GreenpaladiumchestguiMenu> GREENPALADIUMCHESTGUI = register("greenpaladiumchestgui", (id, inv, extraData) -> new GreenpaladiumchestguiMenu(id, inv, extraData));
	public static final MenuType<EndiumchestguiMenu> ENDIUMCHESTGUI = register("endiumchestgui", (id, inv, extraData) -> new EndiumchestguiMenu(id, inv, extraData));
	public static final MenuType<OrelayerfatMenu> ORELAYERFAT = register("orelayerfat", (id, inv, extraData) -> new OrelayerfatMenu(id, inv, extraData));
	public static final MenuType<DownloaderguiMenu> DOWNLOADERGUI = register("downloadergui", (id, inv, extraData) -> new DownloaderguiMenu(id, inv, extraData));
	public static final MenuType<DownloaderlinkMenu> DOWNLOADERLINK = register("downloaderlink", (id, inv, extraData) -> new DownloaderlinkMenu(id, inv, extraData));
	public static final MenuType<PotgtranfertMenu> POTGTRANFERT = register("potgtranfert", (id, inv, extraData) -> new PotgtranfertMenu(id, inv, extraData));
	public static final MenuType<TrixiumdepositMenu> TRIXIUMDEPOSIT = register("trixiumdeposit", (id, inv, extraData) -> new TrixiumdepositMenu(id, inv, extraData));
	public static final MenuType<Examplecrusherv2Menu> EXAMPLECRUSHERV_2 = register("examplecrusherv_2", (id, inv, extraData) -> new Examplecrusherv2Menu(id, inv, extraData));
	public static final MenuType<ExampleuploaderguiMenu> EXAMPLEUPLOADERGUI = register("exampleuploadergui", (id, inv, extraData) -> new ExampleuploaderguiMenu(id, inv, extraData));
	public static final MenuType<UploaderguipalahelpMenu> UPLOADERGUIPALAHELP = register("uploaderguipalahelp", (id, inv, extraData) -> new UploaderguipalahelpMenu(id, inv, extraData));
	public static final MenuType<GrindersplitentityMenu> GRINDERSPLITENTITY = register("grindersplitentity", (id, inv, extraData) -> new GrindersplitentityMenu(id, inv, extraData));

	private static <T extends AbstractContainerMenu> MenuType<T> register(String registryname, IContainerFactory<T> containerFactory) {
		MenuType<T> menuType = new MenuType<T>(containerFactory);
		menuType.setRegistryName(registryname);
		REGISTRY.add(menuType);
		return menuType;
	}

	@SubscribeEvent
	public static void registerContainers(RegistryEvent.Register<MenuType<?>> event) {
		event.getRegistry().registerAll(REGISTRY.toArray(new MenuType[0]));
	}
}
